name: sundial
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rive: ^0.13.20
  flutter_launcher_icons: 0.14.3
  http: ^0.13.6
  intl: ^0.18.0
  provider: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/gradient_background.jpeg
    - assets/images/gradient_background.jpg
    - assets/icon/logograph.png
  fonts:
    - family: GothamRounded
      fonts:
        - asset: fonts/gotham-rounded/gothamrnd_bold.otf
          weight: 700
        - asset: fonts/gotham-rounded/gothamrnd_bolditalic.otf
          style: italic
          weight: 700
        - asset: fonts/gotham-rounded/gothamrnd_book.otf
          weight: 400
        - asset: fonts/gotham-rounded/gothamrnd_bookitalic.otf
          style: italic
          weight: 400
        - asset: fonts/gotham-rounded/gothamrnd_light.otf
          weight: 300
        - asset: fonts/gotham-rounded/gothamrnd_lightitalic.otf
          style: italic
          weight: 300
        - asset: fonts/gotham-rounded/gothamrnd_medium.otf
          weight: 500
        - asset: fonts/gotham-rounded/gothamrnd_mediumitalic.otf
          style: italic
          weight: 500
